---
containers: []
virtualmachines:
  - name: "host1"
    image: "rhel-9.6"
    memory: "8G"
    cores: 2
    image_size: "50G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
